#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mastofessb"
name = "Masto-FE (🦥 flavour)"
description.en = "A fork of IceShrimp's Masto-FE Standalone made to work smoothly and intuitively with a GoToSocial instance as the backend and tweaked with GoToSocial-specific features"
description.fr = "Un fork de Masto-FE Standalone d'IceShrimp conçu pour fonctionner de manière fluide et intuitive avec une instance GoToSocial comme backend et peaufiné avec des fonctionnalités spécifiques à GoToSocial"

version = "20250714~ynh1"

maintainers = ["trendless"]

[upstream]
license = "AGPL-3.0"
demo = "https://masto-fe.superseriousbusiness.org/"
code = "https://codeberg.org/superseriousbusiness/masto-fe-standalone"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "false"
sso = "false"

disk = "1G"
ram.build = "1G"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/masto-fe"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/trendless/ex_ynh/raw/refs/heads/main/ynh-release/masto-fe-standalone-main-110c8fb8cc.tar.gz"
        sha256 = "7a68f8d562ecd882af76e46efd902814ae039206cb8cb2535fd7f85364d4365c"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = ".*\\.tar\\.gz"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]

        [resources.apt.extras.yarn]
        repo = "deb https://dl.yarnpkg.com/debian/ stable main"
        key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
        packages = "yarn"

    [resources.nodejs]
    version = "20"