#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."
ynh_setup_source --dest_dir="$install_dir" --full_replace
chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."
ynh_config_add_nginx
yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"
ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"